/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:da192da4-75c4-4656-a355-11b48e72a390",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_ZpAH09Qnz",
    "aws_user_pools_web_client_id": "66g18ss9sptjf611vi9f63p0i5",
    "oauth": {}
};


export default awsmobile;
