/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:da192da4-75c4-4656-a355-11b48e72a390",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_ZpAH09Qnz",
    "aws_user_pools_web_client_id": "66g18ss9sptjf611vi9f63p0i5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://e25oaxhwyvhlhjlifkl4vc2sge.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-lwkwmd6665djnlrajcvgdcwx44",
    "aws_user_files_s3_bucket": "datarealtime1bee1a5ebba64af881e49b662a09a774194735-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
